#!/usr/bin/env ruby

forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'

mod 'apache',
    :git => 'https://github.com/puppetlabs/puppetlabs-apache.git'

mod "apt",
    :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod 'composer',
    :git => 'https://github.com/Brainsware/puppet-composer.git'

mod 'codeception',
    :git => 'https://github.com/cillosis/puppet-codeception.git'

mod 'git',
    :git => 'https://github.com/puppetlabs/puppetlabs-git.git'

mod 'nodejs',
    :git => 'https://github.com/puppetlabs/puppetlabs-nodejs.git'

mod 'mysql',
    :git => 'https://github.com/puppetlabs/puppetlabs-mysql.git'

mod 'php',
    :git => 'https://github.com/woss/puppet-php.git'